[package]
name = "tilt_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = "4.5.35"
reqwest = { version = "0.11.27", features = ["multipart"] }
tokio = { version = "1.44.1", features = ["full"] }
